'use client';

import { useState, useEffect } from 'react';
import Link from 'next/link';
import { ChevronRight, MapPin, Calendar, ArrowRight, MessageCircle, Eye } from 'lucide-react';
import { Isotipo } from '@/components/ui/isotipo';
import { siteConfig } from '@/config/site';
import { formatWhatsAppUrl } from '@/lib/utils';

type ProjectCategory = 'todos' | 'civil' | 'metalurgica' | 'mantenimiento';
const categories: { id: ProjectCategory; label: string }[] = [
  { id: 'todos', label: 'Todos' }, { id: 'civil', label: 'Construcción civil' }, { id: 'metalurgica', label: 'Metalúrgica' }, { id: 'mantenimiento', label: 'Mantenimiento' },
];
interface Project { id:string; title:string; description:string; category:ProjectCategory; location:string; duration:string; year:string; client:string; badge:'blue'|'green'|'yellow'; size:'large'|'normal'; image:string; }
const defaultProjects: Project[] = [
  {id:'1',title:'Remodelación completa oficinas corporativas',description:'Remodelación integral de 800m2 de oficinas. Incluyó demolición parcial, nueva distribución, instalación eléctrica, pintura y acabados.',category:'civil',location:'Asunción, Paraguay',duration:'3 meses',year:'2025',client:'Empresa multinacional',badge:'blue',size:'large',image:''},
  {id:'2',title:'Nave industrial 1200m2',description:'Diseño, fabricación y montaje de estructura metálica para nave industrial. Incluyó cubierta, cerramientos laterales y portones.',category:'metalurgica',location:'Luque, Paraguay',duration:'4 meses',year:'2025',client:'Industria alimenticia',badge:'green',size:'large',image:''},
  {id:'3',title:'Mantenimiento preventivo edificio comercial',description:'Contrato anual de mantenimiento preventivo para edificio de 12 pisos.',category:'mantenimiento',location:'San Lorenzo, Paraguay',duration:'12 meses',year:'2024-2025',client:'Administración de edificio',badge:'yellow',size:'normal',image:''},
  {id:'4',title:'Portones automáticos residenciales',description:'Fabricación e instalación de portones corredizos automáticos para conjunto residencial de 24 unidades.',category:'metalurgica',location:'Lambaré, Paraguay',duration:'2 meses',year:'2025',client:'Constructora residencial',badge:'green',size:'normal',image:''},
  {id:'5',title:'Construcción vivienda minimalista',description:'Construcción llave en mano de vivienda unifamiliar de 180m2.',category:'civil',location:'Fernando de la Mora',duration:'6 meses',year:'2024',client:'Propietario particular',badge:'blue',size:'large',image:''},
  {id:'6',title:'Instalación eléctrica completa fábrica',description:'Instalación de tablero principal, sub-tableros, cableado industrial e iluminación LED.',category:'mantenimiento',location:'Capiatá, Paraguay',duration:'1 mes',year:'2025',client:'Fábrica textil',badge:'yellow',size:'normal',image:''},
];
const badgeClass = {blue:'badge-blue',green:'badge-green',yellow:'badge-yellow'};
const categoryLabel: Record<ProjectCategory,string> = {todos:'Todos',civil:'Construcción civil',metalurgica:'Metalúrgica',mantenimiento:'Mantenimiento'};

export default function PortfolioPage() {
  const [activeCategory,setActiveCategory]=useState<ProjectCategory>('todos');
  const [projects,setProjects]=useState(defaultProjects);
  useEffect(()=>{fetch('/api/portfolio?active=true').then(r=>r.json()).then(d=>{if(d.projects?.length>0)setProjects(d.projects)}).catch(()=>{});},[]);
  const filtered=activeCategory==='todos'?projects:projects.filter(p=>p.category===activeCategory);
  const whatsappUrl=formatWhatsAppUrl(siteConfig.whatsapp,'Hola, vi su portfolio y me gustaria consultar sobre un proyecto similar.');
  return <>
    <div className="border-b border-gray-200 bg-white"><div className="container-main flex items-center gap-2 py-3 font-body text-caption text-[#8094B4]"><Link href="/" className="hover:text-[#2D8FCC]">Inicio</Link><ChevronRight className="h-3 w-3"/><span className="font-medium text-[#0B1120]">Portfolio</span></div></div>
    <section className="relative overflow-hidden border-b border-gray-200 bg-[#0B1120] py-20 md:py-24"><div className="container-main relative"><span className="overline text-[#7CC4EF]">Nuestro trabajo</span><h1 className="mt-3 max-w-3xl font-display text-[clamp(2.4rem,6vw,4.8rem)] font-bold uppercase leading-[.92] tracking-tight text-white">Proyectos que hablan por nosotros</h1><p className="mt-6 max-w-2xl font-body text-body-lg leading-relaxed text-[#C0CEDF]">Una selección de obras y servicios realizados con foco en calidad, seguridad y cumplimiento.</p></div></section>
    <section className="sticky top-[95px] z-40 border-b border-gray-200 bg-white/95 backdrop-blur-lg"><div className="container-main flex gap-1 overflow-x-auto py-3">{categories.map(cat=><button key={cat.id} onClick={()=>setActiveCategory(cat.id)} className={`min-h-[44px] whitespace-nowrap rounded-lg px-5 py-3 font-body text-[.75rem] font-semibold uppercase tracking-[.04em] transition-all ${activeCategory===cat.id?'bg-[#0B1120] text-white shadow-sm':'text-[#8094B4] hover:bg-[#F4F7FB] hover:text-[#0B1120]'}`}>{cat.label}</button>)}</div></section>
    <section className="section bg-[#F4F7FB]"><div className="container-main"><div className="mb-7 flex items-center justify-between"><span className="overline">Experiencia comprobada</span><span className="font-body text-body-sm text-[#8094B4]">{filtered.length} proyecto{filtered.length!==1?'s':''}</span></div><div className="grid grid-cols-1 gap-6 md:grid-cols-2 lg:grid-cols-3">{filtered.map(project=><article key={project.id} className="card-interactive group overflow-hidden"><div className="relative flex h-56 items-center justify-center overflow-hidden bg-gradient-to-br from-[#EBF5FB] to-white"><Isotipo size={92} color="#2D8FCC18"/><div className="absolute inset-0 bg-gradient-to-t from-[#0B1120]/35 to-transparent opacity-0 transition-opacity group-hover:opacity-100"/><div className="absolute right-4 top-4"><span className={badgeClass[project.badge]}>{categoryLabel[project.category]}</span></div><div className="absolute bottom-4 left-4 flex h-10 w-10 translate-y-2 items-center justify-center rounded-full bg-white opacity-0 shadow-lg transition-all group-hover:translate-y-0 group-hover:opacity-100"><Eye className="h-4 w-4 text-[#2D8FCC]"/></div></div><div className="p-5"><h2 className="font-display text-h3 leading-tight text-[#0B1120]">{project.title}</h2><p className="mt-2 line-clamp-2 font-body text-body-sm leading-relaxed text-[#4A5E80]">{project.description}</p><div className="mt-5 grid grid-cols-2 gap-3 border-t border-gray-200 pt-4"><div className="flex gap-2"><MapPin className="mt-0.5 h-3.5 w-3.5 shrink-0 text-[#2D8FCC]"/><span className="font-body text-caption text-[#4A5E80]">{project.location}</span></div><div className="flex gap-2"><Calendar className="mt-0.5 h-3.5 w-3.5 shrink-0 text-[#2D8FCC]"/><span className="font-body text-caption text-[#4A5E80]">{project.duration} · {project.year}</span></div></div><p className="mt-3 font-body text-caption text-[#8094B4]">Cliente: <span className="text-[#4A5E80]">{project.client}</span></p></div></article>)}</div></div></section>
    <section className="border-t border-gray-200 bg-white py-16"><div className="container-main text-center"><span className="overline">¿Tenés un proyecto?</span><h2 className="mt-2 font-display text-h2 text-[#0B1120]">Hagámoslo realidad</h2><p className="mx-auto mt-3 max-w-md font-body text-body text-[#4A5E80]">Contanos qué necesitás y te preparamos un presupuesto personalizado.</p><div className="mt-6 flex flex-wrap justify-center gap-3"><Link href="/contacto?tipo=presupuesto" className="btn-primary">Pedir presupuesto <ArrowRight className="h-4 w-4"/></Link><a href={whatsappUrl} target="_blank" rel="noopener noreferrer" className="btn-whatsapp"><MessageCircle className="h-4 w-4"/> WhatsApp</a></div></div></section>
  </>;
}
